version: '3.1'
services:
  backend:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app/backend
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm run dev"
    ports:
      - 3001:3001
  frontend:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app/frontend
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: "npm start"
    ports:
      - 3000:3000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5433
    command: -p 5433